#!/bin/bash

set -u
set -e

name=$1
if [ ! $name = "ttbb" ] && [ ! $name = "tb" ]
then
    >&2 echo "process must be ttbb or tb"
else
    jobname=run_${name}_$(date --iso=seconds)
    echo "==> submitting job: $name as $jobname"
fi

njobs=${NJOBS-10}

qsub -N $name \
     -v "NAME=$name,JOBNAME=$jobname,NJOBS=$njobs" \
     -d /lcg/storage15/atlas/gagnon/work \
     -j oe \
     -l nodes=1:ppn=$njobs,nice=0 \
     $PWD/launch.sh
